{
    'name': 'Website Status Checker',
    'version': '1.0',
    'summary': 'Module to check website status',
    'category': 'Tools',
    'author': 'Duy Hung',
    'depends': ['base','os_telegram','mail','contacts_zalo','odoo_integrate_zalo'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/views_ip_wan.xml',
        # 'data/email_template.xml',
        # 'data/server_action.xml',
        'views/disk_info.xml',
        'views/http_response.xml',
        'views/loginattempt.xml',
        'views/port_response.xml',
        'views/telegraf_data_view.xml',
        'views/disk_chart_view.xml',
    ],
    'images': ['check_erro/static/src/img/logo.png'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'assets': {
        'web.assets_backend': [
            'check_erro/static/src/css/kanban_style.css',
            '/web/static/lib/Chart/Chart.js',
            ('include', 'web.chartjs_lib'),
            'check_erro/static/src/js/disk_chart_widget.js',
            'check_erro/static/src/xml/disk_chart_template.xml',
        ],
    },
}
